# Generated by Django 5.2.5 on 2025-08-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photos',
            field=models.ManyToManyField(blank=True, default=False, related_name='collection', to='pixel_app.photo'),
        ),
    ]
