# Generated by Django 5.2.5 on 2025-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0002_alter_collection_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='collection', to='pixel_app.photo'),
        ),
    ]
